fixtures:
  repositories:
    apache: git://github.com/puppetlabs/puppetlabs-apache.git 
    mysql: git://github.com/puppetlabs/puppetlabs-mysql.git
    memcached: git://github.com/saz/puppet-memcached.git
  symlinks:
    mediawiki: "#{source_dir}"
